version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_ais
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: platform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest  # pgAdmin image
    container_name: pgadmin_ais
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with a strong password
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    depends_on:
      - postgres

volumes:
  postgres_data:

