server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: youralias

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

  application:
    name: backend_ais_platform
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
